export const SEARCH_PLACEHOLDER_KEYWORDS = [
  'Vanilla Latte',
  'Starbucks',
  'The Blue Scorcher',
  'Insomnia',
  'Dutch',
  'Blackrock',
  'Flat White',
  'Smoothie',
  'Caramel',
  'Frappucino',
  'Mocha',
  'Oat milk',
  'Lavender',
];
